# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f9fe21c84ae00bec1f2c299ba9567b5697d06f3fce797b438e6dc486500f563c9a876375700512d6583c7c85bd4bdcec0a98f2051d444ed409bafe0c3db581a

test:
  secret_key_base: d0fbbb9c37c4a634745a738280abd0f56e3ac2fdc90072fbe36a7d95feccb4511aef656e6090241be0e2f3ff5f3b0e32d8f9c213c54b18f3cc6777d94e7a97a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
